- name: Setup test env
  hosts: vmhosts
  remote_user: root
  vars_files:
  - vars/all.yml
  roles:
  - vm-host-network
  - vm-host-install
  - vm-host-services

- name: Setup disk2 if enabled
  hosts: vmhosts
  remote_user: root
  vars_files:
  - vars/all.yml
  roles:
  - vm-host-disk2-mount-setup
